import React, {useEffect, useMemo, useState} from "react";
import {useStore, useEvent} from "effector-react";
import { withStart } from "effector-next";


import { $data, pageLoaded, buttonClicked, effect } from "../models";
import Link from "next/link";
import {useSomeData} from "../controller/testDL/hooks";
import {globalDomain} from "../models/model";



const enhance = withStart(pageLoaded);

function HomePage() {
    const [text, setText] = useState<{name: string}| null>(null)
    // const data = useStore($data);
    const handleClick = useEvent(buttonClicked);
    // const loading = useStore(effect.pending)
    const params = useMemo(() => ({}), [])
    // @ts-ignore
    const {entity, fetch} = useSomeData({
        fetchConfig:params,
    })

    const params2 = useMemo(() => ({id: 1}), [])
    // @ts-ignore
    const {entity: entity2, fetch: fetch2} = useSomeData({
        fetchConfig: {
            pathParams: params2
        },
    })



    useEffect(() => {
        // @ts-ignore
        fetch()
    },[])
    useEffect(() => {
        // @ts-ignore
        fetch2()
    },[])



    return (
        <div>
            <h1>HomePage</h1>
            <h2>Store state: {entity?.text ?? 'hello'}</h2>
            <h2>Store state: {entity2?.text ?? 'hello2'}</h2>
            <button onClick={fetch}>click to change store state</button>
            <button onClick={fetch2}>click to change store state</button>

            <br />
            <br />
            <Link href="/static">
                to static page
            </Link>
        </div>
    );
}


export default enhance(HomePage);


// import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })
//
// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>
//
//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>
//
//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>
//
//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>
//
//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>
//
//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
//

